name: Generate Snake

on:
  schedule: # Runs every 24 hours
    - cron: "0 0 * * *"
  workflow_dispatch: # Allows manual runs

# ✅ Allow workflow to push changes
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Generate snake.svg
        uses: Platane/snk@v3
        with:
          github_user_name: blesoh
          outputs: output/github-contribution-grid-snake.svg output/github-contribution-grid-snake-dark.svg

      - name: Push generated files
        uses: EndBug/add-and-commit@v9
        with:
          author_name: github-actions
          author_email: github-actions@github.com
          message: "Generated contribution snake"
          add: "output/*"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
